import React, { useCallback, useEffect, useMemo, useState } from "react";
import { useAuth } from "@clerk/clerk-react";
import AdminLayout from "../../components/AdminLayout/AdminLayout";
import { AlertCircle, CheckCircle2, Download, FileText, Loader2, Plus, Search, Send, Trash2, X } from "lucide-react";
import { createAdminRadiologyReport, deleteAdminRadiologyReport, fetchAdminRadiologyReports } from "../../api/staffRadiologyReportApi";

const reportTypes=["All","X-Ray","MRI","CT Scan","Ultrasound","Other"], statuses=["All","Pending","Completed","Reviewed"], createTypes=reportTypes.slice(1), createStatuses=statuses.slice(1);
const empty={patientId:"",doctorId:"",appointmentId:"",admissionId:"",serviceAppointmentId:"",reportType:"X-Ray",title:"",description:"",findings:"",impression:"",reportDate:"",fileUrl:"",fileName:"",status:"Completed",notes:""};
const inputClass="h-11 w-full rounded-2xl border border-[#dbe6f7] bg-[#f8fbff] px-4 text-sm outline-none focus:border-blue-300 focus:bg-white"; const id=(x={})=>x._id||x.id||""; const date=v=>{const d=v?new Date(v):null;return d&&!Number.isNaN(d.getTime())?d.toLocaleDateString(): "-"}; const name=x=>x?.name||x?.email||x?.patientCode||"Patient";

export default function RadiologyReports(){
 const {getToken}=useAuth(); const [reports,setReports]=useState([]),[filters,setFilters]=useState({search:"",reportType:"All",status:"All"}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[msg,setMsg]=useState({type:"",text:""}),[open,setOpen]=useState(false),[form,setForm]=useState(empty);
 const load=useCallback(async()=>{try{setLoading(true);const body=await fetchAdminRadiologyReports(filters,getToken);setReports(Array.isArray(body.data)?body.data:[])}catch(e){setReports([]);setMsg({type:"error",text:e.message||"Unable to load reports."})}finally{setLoading(false)}},[filters,getToken]); useEffect(()=>{load()},[load]);
 const summary=useMemo(()=>({total:reports.length,completed:reports.filter(r=>r.status==="Completed").length,pending:reports.filter(r=>r.status==="Pending").length,reviewed:reports.filter(r=>r.status==="Reviewed").length}),[reports]);
 async function submit(e){e.preventDefault();try{setSaving(true);const payload=Object.fromEntries(Object.entries(form).filter(([,v])=>v!==""));const body=await createAdminRadiologyReport(payload,getToken);setMsg({type:"success",text:body.message||"Created."});setOpen(false);setForm(empty);await load()}catch(err){setMsg({type:"error",text:err.message||"Unable to create report."})}finally{setSaving(false)}}
 async function remove(r){if(!window.confirm(`Delete ${r.reportCode}?`))return;try{const body=await deleteAdminRadiologyReport(id(r),getToken);setMsg({type:"success",text:body.message||"Deleted."});await load()}catch(e){setMsg({type:"error",text:e.message||"Unable to delete."})}}
 return <AdminLayout title="Radiology Reports" subtitle="View all radiology reports and create patient imaging records."><div className="grid gap-5"><button onClick={()=>setOpen(true)} className="w-fit rounded-2xl bg-blue-600 px-4 py-3 text-sm font-bold text-white"><Plus className="mr-2 inline h-4 w-4"/>Create Report</button><section className="grid gap-4 sm:grid-cols-4"><Stat label="Total" v={summary.total}/><Stat label="Completed" v={summary.completed}/><Stat label="Pending" v={summary.pending}/><Stat label="Reviewed" v={summary.reviewed}/></section><section className="rounded-3xl border border-[#dbe6f7] bg-white p-4"><div className="grid gap-3 lg:grid-cols-[1fr_180px_180px]"><div className="relative"><Search className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input className={`${inputClass} pl-11`} value={filters.search} onChange={e=>setFilters(p=>({...p,search:e.target.value}))}/></div><Select value={filters.reportType} options={reportTypes} onChange={reportType=>setFilters(p=>({...p,reportType}))}/><Select value={filters.status} options={statuses} onChange={status=>setFilters(p=>({...p,status}))}/></div></section>{msg.text?<Notice msg={msg} close={()=>setMsg({type:"",text:""})}/>:null}<section className="rounded-3xl border border-[#dbe6f7] bg-white">{loading?<div className="p-12 text-center text-blue-700"><Loader2 className="inline h-5 w-5 animate-spin"/> Loading...</div>:reports.length===0?<div className="p-12 text-center"><FileText className="mx-auto h-12 w-12 text-blue-700"/><b>No radiology reports found.</b></div>:<div className="overflow-x-auto"><table className="min-w-full text-sm"><tbody>{reports.map(r=><tr key={id(r)} className="border-b"><td className="p-4"><b className="text-blue-700">{r.reportCode}</b><p>{r.title}</p><small>{r.reportType} | {r.status}</small></td><td className="p-4">{name(r.patientId)}</td><td className="p-4">{date(r.reportDate)}</td><td className="p-4"><button onClick={()=>remove(r)} className="rounded-xl bg-rose-50 px-3 py-2 font-bold text-rose-700"><Trash2 className="inline h-4 w-4"/> Delete</button>{r.fileUrl?<a href={r.fileUrl} target="_blank" rel="noreferrer" className="ml-2 rounded-xl bg-blue-600 px-3 py-2 font-bold text-white"><Download className="inline h-4 w-4"/> File</a>:null}</td></tr>)}</tbody></table></div>}</section></div>{open?<Form form={form} setForm={setForm} submit={submit} saving={saving} close={()=>setOpen(false)}/>:null}</AdminLayout>
}
function Select({value,options,onChange}){return <select className={inputClass} value={value} onChange={e=>onChange(e.target.value)}>{options.map(x=><option key={x}>{x}</option>)}</select>}
function Stat({label,v}){return <div className="rounded-3xl border border-[#dbe6f7] bg-white p-4"><p className="text-xs font-black uppercase text-slate-400">{label}</p><p className="mt-2 text-2xl font-black text-blue-700">{v}</p></div>}
function Notice({msg,close}){const ok=msg.type==="success";return <div className={`flex justify-between rounded-2xl border p-4 text-sm font-bold ${ok?"border-emerald-100 bg-emerald-50 text-emerald-700":"border-rose-100 bg-rose-50 text-rose-700"}`}><span>{ok?<CheckCircle2 className="mr-2 inline h-4 w-4"/>:<AlertCircle className="mr-2 inline h-4 w-4"/>}{msg.text}</span><button onClick={close}><X className="h-4 w-4"/></button></div>}
function Form({form,setForm,submit,saving,close}){return <div className="fixed inset-0 z-[80] flex items-end justify-center bg-slate-950/45 px-3 py-4 sm:items-center"><form onSubmit={submit} className="max-h-[92vh] w-full max-w-4xl overflow-y-auto rounded-3xl bg-white p-5 shadow-2xl"><div className="flex justify-between"><h2 className="text-xl font-black">Create Radiology Report</h2><button type="button" onClick={close}><X/></button></div><p className="mt-1 text-sm text-slate-500">Use real IDs and a fileUrl if a report file exists.</p><div className="mt-5 grid gap-4 md:grid-cols-2">{["patientId","doctorId","appointmentId","admissionId","serviceAppointmentId","title","fileUrl","fileName"].map(k=><label key={k} className="grid gap-1 text-sm font-bold">{k}<input required={k==="patientId"||k==="title"} className={inputClass} value={form[k]} onChange={e=>setForm(p=>({...p,[k]:e.target.value}))}/></label>)}<label className="grid gap-1 text-sm font-bold">Report Type<Select value={form.reportType} options={createTypes} onChange={reportType=>setForm(p=>({...p,reportType}))}/></label><label className="grid gap-1 text-sm font-bold">Status<Select value={form.status} options={createStatuses} onChange={status=>setForm(p=>({...p,status}))}/></label>{["description","findings","impression","notes"].map(k=><label key={k} className="grid gap-1 text-sm font-bold md:col-span-2">{k}<textarea className={`${inputClass} min-h-20 py-3`} value={form[k]} onChange={e=>setForm(p=>({...p,[k]:e.target.value}))}/></label>)}</div><div className="mt-5 flex justify-end gap-3"><button type="button" onClick={close} className="h-11 rounded-2xl border px-4 font-bold">Cancel</button><button disabled={saving} className="h-11 rounded-2xl bg-blue-600 px-4 font-bold text-white"><Send className="mr-2 inline h-4 w-4"/>Create</button></div></form></div>}
