import React, { useCallback, useEffect, useMemo, useState } from "react";
import { AlertCircle, CheckCircle2, Download, Eye, FileText, Loader2, Plus, Search, Send, X } from "lucide-react";
import { fetchDoctorLabReports, requestDoctorLabReport } from "../../api/labReportApi";

const testTypes = ["All", "Blood Test", "Urine Test", "Diabetes Test", "Cholesterol Test", "Infection Test", "Other"];
const createTypes = testTypes.slice(1);
const statuses = ["All", "Requested", "In Progress", "Completed", "Reviewed"];
const empty = { patientId: "", appointmentId: "", admissionId: "", serviceAppointmentId: "", testType: "Blood Test", title: "", description: "", specimen: "", requestedDate: "", notes: "" };
const inputClass = "h-11 w-full rounded-2xl border border-[#dbe6f7] bg-[#f8fbff] px-4 text-sm text-slate-800 outline-none focus:border-blue-300 focus:bg-white";
const id = (x={}) => x._id || x.id || ""; const date = v => { const d=v?new Date(v):null; return d&&!Number.isNaN(d.getTime())?d.toLocaleDateString(): "-"; }; const patient = x => x?.name||x?.email||x?.phone||x?.patientCode||"Patient";
function Badge({children}){return <span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-700 ring-1 ring-blue-100">{children}</span>}

export default function LabReports(){
 const [reports,setReports]=useState([]),[filters,setFilters]=useState({search:"",testType:"All",status:"All"}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[msg,setMsg]=useState({type:"",text:""}),[open,setOpen]=useState(false),[form,setForm]=useState(empty),[selected,setSelected]=useState(null);
 const load=useCallback(async()=>{try{setLoading(true);const body=await fetchDoctorLabReports(filters);setReports(Array.isArray(body.data)?body.data:[])}catch(e){setReports([]);setMsg({type:"error",text:e.message||"Unable to load lab reports."})}finally{setLoading(false)}},[filters]);
 useEffect(()=>{load()},[load]);
 const summary=useMemo(()=>({total:reports.length,requested:reports.filter(r=>r.status==="Requested").length,completed:reports.filter(r=>r.status==="Completed").length,reviewed:reports.filter(r=>r.status==="Reviewed").length}),[reports]);
 async function submit(e){e.preventDefault();try{setSaving(true);const payload=Object.fromEntries(Object.entries(form).filter(([,v])=>v!==""));const body=await requestDoctorLabReport(payload);setMsg({type:"success",text:body.message||"Lab test requested."});setOpen(false);setForm(empty);await load()}catch(err){setMsg({type:"error",text:err.message||"Unable to request lab test."})}finally{setSaving(false)}}
 return <div className="px-4 py-6 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-5"><header className="flex flex-col gap-4 rounded-3xl border border-[#dbe6f7] bg-white p-5 shadow-sm md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-black uppercase tracking-[0.14em] text-blue-700">Doctor Workspace</p><h1 className="mt-2 text-3xl font-black text-slate-950">Lab Reports</h1><p className="mt-1 text-sm text-slate-500">Request lab tests and review results.</p></div><button onClick={()=>setOpen(true)} className="inline-flex h-11 items-center gap-2 rounded-2xl bg-blue-600 px-4 text-sm font-bold text-white"><Plus className="h-4 w-4"/>Request Test</button></header><section className="grid gap-4 sm:grid-cols-4">{Object.entries(summary).map(([k,v])=><Stat key={k} label={k} value={v}/>)}</section><section className="rounded-3xl border border-[#dbe6f7] bg-white p-4"><div className="grid gap-3 md:grid-cols-[1fr_210px_180px]"><div className="relative"><Search className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input className={`${inputClass} pl-11`} value={filters.search} onChange={e=>setFilters(p=>({...p,search:e.target.value}))} placeholder="Search lab reports..."/></div><Select value={filters.testType} options={testTypes} onChange={testType=>setFilters(p=>({...p,testType}))}/><Select value={filters.status} options={statuses} onChange={status=>setFilters(p=>({...p,status}))}/></div></section>{msg.text?<Notice msg={msg} close={()=>setMsg({type:"",text:""})}/>:null}<section className="rounded-3xl border border-[#dbe6f7] bg-white shadow-sm">{loading?<div className="p-12 text-center text-sm font-bold text-blue-700"><Loader2 className="mr-2 inline h-5 w-5 animate-spin"/>Loading lab reports...</div>:reports.length===0?<Empty/>:<div className="grid gap-3 p-4">{reports.map(r=><article key={id(r)} className="rounded-2xl border border-slate-100 p-4"><div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between"><div><div className="flex flex-wrap gap-2"><span className="font-black text-blue-700">{r.reportCode}</span><Badge>{r.testType}</Badge><Badge>{r.status}</Badge></div><h2 className="mt-2 font-black text-slate-950">{r.title}</h2><p className="mt-1 text-sm text-slate-500">{patient(r.patientId)} | Requested {date(r.requestedDate)}</p></div><div className="flex gap-2"><button onClick={()=>setSelected(r)} className="rounded-2xl bg-blue-50 px-4 py-2 text-sm font-bold text-blue-700"><Eye className="mr-1 inline h-4 w-4"/>View</button>{r.fileUrl?<a href={r.fileUrl} target="_blank" rel="noreferrer" className="rounded-2xl bg-blue-600 px-4 py-2 text-sm font-bold text-white"><Download className="mr-1 inline h-4 w-4"/>File</a>:null}</div></div></article>)}</div>}</section></div>{open?<RequestForm form={form} setForm={setForm} saving={saving} submit={submit} close={()=>setOpen(false)}/>:null}{selected?<Detail r={selected} close={()=>setSelected(null)}/>:null}</div>
}
function Select({value,options,onChange}){return <select className={inputClass} value={value} onChange={e=>onChange(e.target.value)}>{options.map(x=><option key={x}>{x}</option>)}</select>}
function Stat({label,value}){return <div className="rounded-3xl border border-[#dbe6f7] bg-white p-4"><p className="text-xs font-black uppercase tracking-[0.12em] text-slate-400">{label}</p><p className="mt-2 text-2xl font-black text-blue-700">{value}</p></div>}
function Notice({msg,close}){const ok=msg.type==="success";return <div className={`flex justify-between rounded-2xl border p-4 text-sm font-bold ${ok?"border-emerald-100 bg-emerald-50 text-emerald-700":"border-rose-100 bg-rose-50 text-rose-700"}`}><span>{ok?<CheckCircle2 className="mr-2 inline h-4 w-4"/>:<AlertCircle className="mr-2 inline h-4 w-4"/>}{msg.text}</span><button onClick={close}><X className="h-4 w-4"/></button></div>}
function Empty(){return <div className="p-12 text-center"><FileText className="mx-auto h-12 w-12 text-blue-700"/><h2 className="mt-3 font-black">No lab reports found.</h2></div>}
function RequestForm({form,setForm,saving,submit,close}){return <div className="fixed inset-0 z-[80] flex items-end justify-center bg-slate-950/45 px-3 py-4 sm:items-center"><form onSubmit={submit} className="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-3xl bg-white p-5 shadow-2xl"><div className="flex justify-between"><h2 className="text-xl font-black">Request Lab Test</h2><button type="button" onClick={close}><X/></button></div><p className="mt-1 text-sm text-slate-500">Use a real patientId. Patient lookup UI can be added later.</p><div className="mt-5 grid gap-4 md:grid-cols-2">{["patientId","appointmentId","admissionId","serviceAppointmentId","title","specimen"].map(k=><label key={k} className="grid gap-1 text-sm font-bold">{k}<input required={k==="patientId"||k==="title"} className={inputClass} value={form[k]} onChange={e=>setForm(p=>({...p,[k]:e.target.value}))}/></label>)}<label className="grid gap-1 text-sm font-bold">Test Type<Select value={form.testType} options={createTypes} onChange={testType=>setForm(p=>({...p,testType}))}/></label><label className="grid gap-1 text-sm font-bold">Requested Date<input type="date" className={inputClass} value={form.requestedDate} onChange={e=>setForm(p=>({...p,requestedDate:e.target.value}))}/></label>{["description","notes"].map(k=><label key={k} className="grid gap-1 text-sm font-bold md:col-span-2">{k}<textarea className={`${inputClass} min-h-24 py-3`} value={form[k]} onChange={e=>setForm(p=>({...p,[k]:e.target.value}))}/></label>)}</div><div className="mt-5 flex justify-end gap-3"><button type="button" onClick={close} className="h-11 rounded-2xl border px-4 font-bold">Cancel</button><button disabled={saving} className="h-11 rounded-2xl bg-blue-600 px-4 font-bold text-white"><Send className="mr-2 inline h-4 w-4"/>Request</button></div></form></div>}
function Detail({r,close}){return <div className="fixed inset-0 z-[80] flex items-end justify-center bg-slate-950/45 px-3 py-4 sm:items-center"><div className="max-h-[92vh] w-full max-w-4xl overflow-y-auto rounded-3xl bg-white p-5 shadow-2xl"><div className="flex justify-between"><h2 className="text-xl font-black">{r.reportCode} - {r.title}</h2><button onClick={close}><X/></button></div><div className="mt-4 grid gap-3">{["description","specimen","resultSummary","interpretation","notes"].map(k=><div key={k} className="rounded-2xl bg-slate-50 p-4"><p className="font-black capitalize text-slate-500">{k}</p><p className="mt-1 whitespace-pre-wrap text-sm">{r[k]||"-"}</p></div>)}</div></div></div>}
