import React, { useCallback, useEffect, useMemo, useState } from "react";
import { AlertCircle, CheckCircle2, Download, Eye, FileText, Loader2, Pencil, Plus, Search, Send, Trash2, X } from "lucide-react";
import { StaffPageHeader } from "../../staff/StaffLayout/StaffLayout";
import { createStaffRadiologyReport, deleteStaffRadiologyReport, fetchStaffRadiologyReports, updateStaffRadiologyReport } from "../../api/staffRadiologyReportApi";

const reportTypes=["All","X-Ray","MRI","CT Scan","Ultrasound","Other"], statuses=["All","Pending","Completed","Reviewed"], createTypes=reportTypes.slice(1), createStatuses=statuses.slice(1);
const empty={patientId:"",doctorId:"",appointmentId:"",admissionId:"",serviceAppointmentId:"",reportType:"X-Ray",title:"",description:"",findings:"",impression:"",reportDate:"",fileUrl:"",fileName:"",status:"Completed",notes:""};
const inputClass="h-11 w-full rounded-2xl border border-[#dbe6f7] bg-[#f8fbff] px-4 text-sm text-slate-800 outline-none focus:border-blue-300 focus:bg-white";
const id=(x={})=>x._id||x.id||""; const date=v=>{const d=v?new Date(v):null;return d&&!Number.isNaN(d.getTime())?d.toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"}):"-"}; const patient=x=>x?.name||x?.email||x?.phone||x?.patientCode||"Patient"; const doctor=x=>x?.name||x?.email||"Doctor";
function Badge({children}){return <span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-700 ring-1 ring-blue-100">{children}</span>}

export default function StaffRadiologyReports(){
 const [reports,setReports]=useState([]),[filters,setFilters]=useState({search:"",reportType:"All",status:"All"}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[msg,setMsg]=useState({type:"",text:""}),[modal,setModal]=useState(null),[form,setForm]=useState(empty),[selected,setSelected]=useState(null);
 const load=useCallback(async()=>{try{setLoading(true);const body=await fetchStaffRadiologyReports(filters);setReports(Array.isArray(body.data)?body.data:[])}catch(e){setReports([]);setMsg({type:"error",text:e.message||"Unable to load reports."})}finally{setLoading(false)}},[filters]);
 useEffect(()=>{load()},[load]);
 const summary=useMemo(()=>({total:reports.length,completed:reports.filter(r=>r.status==="Completed").length,pending:reports.filter(r=>r.status==="Pending").length,reviewed:reports.filter(r=>r.status==="Reviewed").length}),[reports]);
 function openCreate(){setForm(empty);setModal("create")} function openEdit(r){setForm({...empty,...r,patientId:id(r.patientId),doctorId:id(r.doctorId),appointmentId:id(r.appointmentId),admissionId:id(r.admissionId),serviceAppointmentId:id(r.serviceAppointmentId),reportDate:r.reportDate?String(r.reportDate).slice(0,10):""});setModal("edit")}
 async function submit(e){e.preventDefault();try{setSaving(true);const payload=Object.fromEntries(Object.entries(form).filter(([,v])=>v!==""&&v!==null&&v!==undefined));const body=modal==="edit"?await updateStaffRadiologyReport(id(form),payload):await createStaffRadiologyReport(payload);setMsg({type:"success",text:body.message||"Saved."});setModal(null);await load()}catch(err){setMsg({type:"error",text:err.message||"Unable to save report."})}finally{setSaving(false)}}
 async function remove(r){if(!window.confirm(`Delete ${r.reportCode||"this report"}?`))return;try{setSaving(true);const body=await deleteStaffRadiologyReport(id(r));setMsg({type:"success",text:body.message||"Deleted."});await load()}catch(e){setMsg({type:"error",text:e.message||"Unable to delete report."})}finally{setSaving(false)}}
 return <div><StaffPageHeader title="Radiology Reports" subtitle="Create, review, edit, and manage patient imaging reports." breadcrumb="Staff Portal / Radiology Reports" action={<button onClick={openCreate} className="inline-flex h-11 items-center gap-2 rounded-2xl bg-blue-600 px-4 text-sm font-bold text-white"><Plus className="h-4 w-4"/>Create Report</button>}/><div className="px-4 py-6 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-5">
  <section className="grid gap-4 sm:grid-cols-4"><Stat label="Total" value={summary.total}/><Stat label="Completed" value={summary.completed}/><Stat label="Pending" value={summary.pending}/><Stat label="Reviewed" value={summary.reviewed}/></section>
  <section className="rounded-3xl border border-[#dbe6f7] bg-white p-4 shadow-sm"><div className="grid gap-3 lg:grid-cols-[1fr_180px_180px]"><div className="relative"><Search className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input className={`${inputClass} pl-11`} value={filters.search} onChange={e=>setFilters(p=>({...p,search:e.target.value}))} placeholder="Search reports..."/></div><Select value={filters.reportType} options={reportTypes} onChange={reportType=>setFilters(p=>({...p,reportType}))}/><Select value={filters.status} options={statuses} onChange={status=>setFilters(p=>({...p,status}))}/></div></section>
  {msg.text?<Notice msg={msg} close={()=>setMsg({type:"",text:""})}/>:null}
  <section className="overflow-hidden rounded-3xl border border-[#dbe6f7] bg-white shadow-sm">{loading?<div className="p-14 text-center text-sm font-bold text-blue-700"><Loader2 className="mr-2 inline h-5 w-5 animate-spin"/>Loading reports...</div>:reports.length===0?<Empty/>:<div className="overflow-x-auto"><table className="min-w-full divide-y divide-slate-100 text-sm"><thead className="bg-[#f8fbff] text-xs uppercase tracking-[0.12em] text-slate-500"><tr><th className="px-5 py-4 text-left">Report</th><th className="px-5 py-4 text-left">Patient</th><th className="px-5 py-4 text-left">Doctor</th><th className="px-5 py-4 text-left">Date</th><th className="px-5 py-4 text-left">Status</th><th className="px-5 py-4 text-left">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{reports.map(r=><tr key={id(r)}><td className="px-5 py-4"><p className="font-black text-blue-700">{r.reportCode}</p><p className="font-bold text-slate-900">{r.title}</p><Badge>{r.reportType}</Badge></td><td className="px-5 py-4">{patient(r.patientId)}</td><td className="px-5 py-4">{doctor(r.doctorId)}</td><td className="px-5 py-4">{date(r.reportDate)}</td><td className="px-5 py-4"><Badge>{r.status}</Badge></td><td className="px-5 py-4"><div className="flex flex-wrap gap-2"><button onClick={()=>setSelected(r)} className="rounded-xl bg-blue-50 px-3 py-2 text-xs font-bold text-blue-700"><Eye className="inline h-3.5 w-3.5"/> View</button><button onClick={()=>openEdit(r)} className="rounded-xl bg-amber-50 px-3 py-2 text-xs font-bold text-amber-700"><Pencil className="inline h-3.5 w-3.5"/> Edit</button><button onClick={()=>remove(r)} className="rounded-xl bg-rose-50 px-3 py-2 text-xs font-bold text-rose-700"><Trash2 className="inline h-3.5 w-3.5"/> Delete</button>{r.fileUrl?<a href={r.fileUrl} target="_blank" rel="noreferrer" className="rounded-xl bg-blue-600 px-3 py-2 text-xs font-bold text-white"><Download className="inline h-3.5 w-3.5"/> File</a>:null}</div></td></tr>)}</tbody></table></div>}</section>
 </div></div>{modal?<ReportForm mode={modal} form={form} setForm={setForm} submit={submit} saving={saving} close={()=>setModal(null)}/>:null}{selected?<Detail r={selected} close={()=>setSelected(null)}/>:null}</div>
}
function Select({value,options,onChange}){return <select className={inputClass} value={value} onChange={e=>onChange(e.target.value)}>{options.map(x=><option key={x}>{x}</option>)}</select>}
function Stat({label,value}){return <div className="rounded-3xl border border-[#dbe6f7] bg-white p-4 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.12em] text-slate-400">{label}</p><p className="mt-2 text-2xl font-black text-blue-700">{value}</p></div>}
function Notice({msg,close}){const ok=msg.type==="success";return <div className={`flex justify-between rounded-2xl border p-4 text-sm font-bold ${ok?"border-emerald-100 bg-emerald-50 text-emerald-700":"border-rose-100 bg-rose-50 text-rose-700"}`}><span>{ok?<CheckCircle2 className="mr-2 inline h-4 w-4"/>:<AlertCircle className="mr-2 inline h-4 w-4"/>}{msg.text}</span><button onClick={close}><X className="h-4 w-4"/></button></div>}
function Empty(){return <div className="p-14 text-center"><FileText className="mx-auto h-12 w-12 text-blue-700"/><h2 className="mt-3 font-black">No radiology reports found.</h2></div>}
function ReportForm({mode,form,setForm,submit,saving,close}){return <div className="fixed inset-0 z-[80] flex items-end justify-center bg-slate-950/45 px-3 py-4 sm:items-center"><form onSubmit={submit} className="max-h-[92vh] w-full max-w-4xl overflow-y-auto rounded-3xl bg-white p-5 shadow-2xl"><div className="flex justify-between"><h2 className="text-xl font-black">{mode==="edit"?"Edit":"Create"} Radiology Report</h2><button type="button" onClick={close}><X/></button></div><p className="mt-1 text-sm text-slate-500">Use a real patientId. File upload is currently a fileUrl field.</p><div className="mt-5 grid gap-4 md:grid-cols-2">{["patientId","doctorId","appointmentId","admissionId","serviceAppointmentId","title","fileUrl","fileName"].map(k=><label key={k} className="grid gap-1 text-sm font-bold">{k}<input disabled={mode==="edit"&&["patientId","doctorId","appointmentId","admissionId","serviceAppointmentId"].includes(k)} required={k==="patientId"||k==="title"} className={inputClass} value={form[k]||""} onChange={e=>setForm(p=>({...p,[k]:e.target.value}))}/></label>)}<label className="grid gap-1 text-sm font-bold">Report Type<Select value={form.reportType} options={createTypes} onChange={reportType=>setForm(p=>({...p,reportType}))}/></label><label className="grid gap-1 text-sm font-bold">Status<Select value={form.status} options={createStatuses} onChange={status=>setForm(p=>({...p,status}))}/></label><label className="grid gap-1 text-sm font-bold">Report Date<input type="date" className={inputClass} value={form.reportDate||""} onChange={e=>setForm(p=>({...p,reportDate:e.target.value}))}/></label>{["description","findings","impression","notes"].map(k=><label key={k} className="grid gap-1 text-sm font-bold md:col-span-2">{k}<textarea className={`${inputClass} min-h-24 py-3`} value={form[k]||""} onChange={e=>setForm(p=>({...p,[k]:e.target.value}))}/></label>)}</div><div className="mt-5 flex justify-end gap-3"><button type="button" onClick={close} className="h-11 rounded-2xl border px-4 font-bold">Cancel</button><button disabled={saving} className="inline-flex h-11 items-center gap-2 rounded-2xl bg-blue-600 px-4 font-bold text-white">{saving?<Loader2 className="h-4 w-4 animate-spin"/>:<Send className="h-4 w-4"/>}Save</button></div></form></div>}
function Detail({r,close}){return <div className="fixed inset-0 z-[80] flex items-end justify-center bg-slate-950/45 px-3 py-4 sm:items-center"><div className="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-3xl bg-white p-5 shadow-2xl"><div className="flex justify-between"><h2 className="text-xl font-black">{r.reportCode} - {r.title}</h2><button onClick={close}><X/></button></div><div className="mt-4 grid gap-3">{["description","findings","impression","notes"].map(k=><div key={k} className="rounded-2xl bg-slate-50 p-4"><p className="font-black capitalize text-slate-500">{k}</p><p className="mt-1 whitespace-pre-wrap text-sm">{r[k]||"-"}</p></div>)}</div></div></div>}
